# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               codeninja55 Deep Learning with Computer Vision Blog
tagline:             ''
description:         'A Computer Science and Data Science student wishing to blog his journey into deep learning with computer vision.'
url:                 https://codeninja55.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Andrew Che
  url:               https://codeninja55.github.io
  email:             andrew@codeninja55.me

# Custom vars
version:             1.0.0
