# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Musings of a Data Scientist
tagline:             ''
description:         'A Computer Science and Data Science student wishing to blog his journey into deep learning with
 computer vision and big data.'
url:                 https://codeninja55.github.io
baseurl:             ''
paginate:            5

social:
github:              codeninja55
linkedin:            andrew-che-1194144b
twitter:             codeninja55
bitbucket:           codeninja55

# About/contact
author:
  name:              Andrew Che
  url:               https://codeninja55.github.io
  email:             andrew@codeninja55.me

# Custom vars
version:             1.0.0
